name: dtbroker_agent
description: Real Estate Broker Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  #  App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

#  Launcher Icon Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"

  # Optional (Recommended for Android 8+ adaptive icons)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/appicon.png"
