name: dtbroker_agent
description: Real Estate Broker Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.2.1
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appstore.png"
  adaptive_icon_foreground: "assets/images/appstore.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
